### ISSUE TITLE
`new_object` and `GlobalRef`

### ISSUE THREAD

**Issue by DarkEld3r** [prevoty/jni-rs#24]
Is there a way to create a new object from the cached `GlobalRef`? As far as I can see, `new_object` expects a class name as string only. Am I missing something?

If this is currently impossible, I can try to fix this (somehow). :sweat_smile:

**Comment by jechas01** [comment]
What are you looking for exactly? Do you want to create a new object from the `GlobalRef` by copying it? Are you trying to get at the object that it points to so that you can do other things with it? Or are you trying to create a new object of the same class?

I believe that #26 should address the second use case, and the third can be accomplished with a new `Desc` impl for `JObject` that calls `get_object_class` behind the scenes.

**Comment by jechas01** [comment]
Judging from your comment on #25, it looks like this was fixed in #26.

Please reopen if I've misjudged!
