### ISSUE TITLE
(Native) context of Java exceptions

### ISSUE THREAD

**Issue by DarkEld3r** [prevoty/jni-rs#46]
Currently `check_exception!` macro returns `JavaException` error which isn't very informative: native (rust) call stack is missed because of `Result` handling logic.

More details: in the situation where there are many `new_object` calls and some of them fail (`NoSuchMethodError`) it isn't clear which one caused problem.

I'm not sure what is the best way to handle such situations. Some ideas:
1. Obviously user can add additional checks after each `new_object` call. This approach requires additional boilerplate.
2. `jni-rs` can include in `Result::Err` some additional information about the JNI call context: the call stack information and method parameters. For example, when [GetMethodId](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetMethodID) fails with a `NoSuchMethodError`, include information about the class, method name and signature.
3. Additional checks can be added to the `new_object` method (and related ones).

Additional question: perhaps, this situation isn't specific only to creating a new Java object, but it relates to the overall error handling strategy.

**Comment by jechas01** [comment]
As far as the rust callstack in the errors goes, it should get generated if you have RUST_BACKTRACE=1 in your environment since error_chain is used for the error types.

For the JavaException errors, would it be useful to include the actual exception in the error? We could use ExceptionOccurred rather than CheckException in the exception-checking macro.

I suppose some extra checks could be added during exception handling that also try to determine the type of exception and then return a more meaningful Rust error, but that could involve some extra overhead that I'm not sure we'd want to incur, since in order to do so would require getting the class of the jthrowable calling the getName method on that, converting to a rust string, and then comparing against some known java exception types. Some of that could be alleviated by caching the getName method (which isn't really supported yet) and using the raw class name unsafely.

Thoughts?

**Comment by DarkEld3r** [comment]
@jechas01 Perhaps I'm missing something here, but do we actually have a backtrace in Rust in our case? I suppose it will work only if we get a panic in Rust. But if we just return `Err` (possibly with `?`), then there will be no backtrace. Did `error_chain` perform some magic here?

**Comment by dmitry-timofeev** [comment]
Regarding some extra work to get the error message of a Java exception in Rust: I agree that this might not be needed often because (a) if you need to handle a Java exception in native code, you will have to use `ExceptionOccurred` to get the object and decide what to do, and then call `ClearException` to tell the JVM that you've caught it; (b) if you don't need to do that, the exception will be thrown in Java, where it's so much easier to get all the information it includes (a stack trace, an error messages, anything else put there during its instantiation).

**Comment by jechas01** [comment]
@DarkEld3r: Yep! take a look at the error_chain docs [here](https://docs.rs/error-chain/0.11.0/error_chain/#backtraces). Backtraces are generated when the environment variable is set as early as possible when creating an `Error`, either by converting a foreign error into one of the error variants or when using `ErrorKind::into`.

And if you look at the [rustdocs](https://docs.rs/jni/0.7.0/jni/errors/struct.Error.html) for our `Error` type, there is indeed a `backtrace` method!
