### ISSUE TITLE
Extend Invocation API support

### ISSUE THREAD

**Issue by dmitry-timofeev** [prevoty/jni-rs#60]
Our team needs a means to launch a JVM from Rust (in C JNI interface that functionality is provided by [the Invocation API](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html), that is already partly supported by jni-rs). I'd like to ask if anybody is currently working on it, and if not, if we could contribute the remaining parts? Are there any nuances we must consider when designing and implementing this functionality?

**Comment by fpoli** [comment]
This is exactly our use case, I'm really interested in this development.

At the moment we are using an adapted version of the [`Jvm::new` function from Rucaja](https://github.com/kud1ing/rucaja/blob/master/src/jvm.rs#L132) to start the JVM, then we switch to `jni-rs` with `JNIEnv::from_raw`. It works fine for us. The only missing part in `jni-rs` is the link to the dynamic library, so we had to:
- add `links = "jvm"` and `build = "build.rs"` to our `Cargo.toml`
- add a `#[link(name = "jvm")] extern "C" {}` somewhere (e.g. `lib.rs`)
- write a `build.rs` that configures the dynamic library location (an example is [here](https://github.com/kud1ing/rucaja/blob/master/build.rs), with a related [issue](https://github.com/kud1ing/rucaja/issues/23))

In general, I think it can be very useful to have a look at [Rucaja](https://github.com/kud1ing/rucaja), because it already implements the "call JVM from Rust" part. A merge of the two would be really great, because most of the functionalities (call a method, call a static method, ...) are duplicated.

**Comment by dmitry-timofeev** [comment]
@fpoli , thank you a lot for the references, we'll definitely look at Rucaja closer to see how to make things work together!

**Comment by jechase** [comment]
OK, let me see if I have this straight, since I haven't looked at the invocation api at all since it's not part of our use case.

1. You want to start a JVM from rust and
2. That requires linking to a the JVM dynamic library

If implemented, it's probably something that we'll want to put behind a cargo feature, since unconditionally requiring linkage to the jvm lib might be undesirable. Otherwise, sounds like a great thing to have, and would make #61 actually doable.

**Comment by jechase** [comment]
I've started work on some additions to the invocation api in the [invocation_api](https://github.com/prevoty/jni-rs/tree/invocation_api) branch. Feel free to comment, test, PR, etc. from there and when we're all satisfied, I'll merge it to master.

**Comment by dmitry-timofeev** [comment]
Hi @jechase , we've used the tip from invocation_api branch for a while in some integration tests, and it seems to work properly. Is there anything you plan to put in it before releasing, maybe something we can help with?

**Comment by jechase** [comment]
Hey, sorry, been out for the holidays. I don't think there was anything else that I was planning to add to it. If everything's been good with it so far, I'll go ahead and merge it :)

**Comment by dmitry-timofeev** [comment]
Works like a charm, thank you a lot!
