### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by fpoli** [prevoty/jni-rs#61]
Having tests is very useful. We could write some integration/system test that:
- initializes a JVM, by calling directly `jni-sys` or the proposed extended invocation API #60 
- builds a `JNIEnv` with `JNIEnv::from_raw`
- test stuff in `JNIEnv`, relaying mainly on JVM builtin classes

An example of the result is [here](https://github.com/kud1ing/rucaja/blob/master/tests/test_jvm_array.rs), from the Rucaja crate.

**Comment by dmitry-timofeev** [comment]
Awesome, such tests organization makes perfect sense: you don't need to write any Java code, compile it, and then run your tests against, you already have everything you might need in the standard library.

I have a question regarding multiple tests in the same file. The Rust docs [say](https://doc.rust-lang.org/book/second-edition/ch11-03-test-organization.html#the-tests-directory) that each IT (a file in `tests`) results in a separate binary and run in a single process, which is great, because you [can](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#JNI_CreateJavaVM) create only a single JVM per process, and can't unload it. But are individual tests run in parallel? If so, the tests have to share a single JVM instance and then each test must attach itself (= get a context -- JNIEnv -- to call the Java code).

**Comment by fpoli** [comment]
In my experiments multiple tests in the same file are run in parallel, and I didn't managed to initialize one JVM for all of them.

**Comment by jechase** [comment]
So if you take a look at the invocation api branch, I made some changes to the initialization of the JavaVM object. Now it's already detached when it gets returned, so in order to use it, you have to call the attach_current_thread method. The benefit of this is that you can now put the VM into lazy_static, and then simply attach it in each of your `#[test]` functions. So parallel tests in a single binary should be possible now! I've also updated the binary search test to use this new method of getting access to the vm.

**Comment by jechase** [comment]
I think this is at least somewhat implemented, at least in the general "we have tests" sense.

If there are more specific tests desired, issues or PRs are welcome!
